### ISSUE TITLE
Prepare code for work

### ISSUE THREAD

**Issue by spksoft** [spksoft/terng.life#1]

**Comment by 0pdd** [comment]
@spksoft 7 puzzles [#2](https://github.com/spksoft/terng.life/issues/2), [#3](https://github.com/spksoft/terng.life/issues/3), [#4](https://github.com/spksoft/terng.life/issues/4), [#5](https://github.com/spksoft/terng.life/issues/5), [#6](https://github.com/spksoft/terng.life/issues/6), [#7](https://github.com/spksoft/terng.life/issues/7), [#8](https://github.com/spksoft/terng.life/issues/8) are still not solved.

**Comment by 0pdd** [comment]
@spksoft 8 puzzles [#2](https://github.com/spksoft/terng.life/issues/2), [#3](https://github.com/spksoft/terng.life/issues/3), [#4](https://github.com/spksoft/terng.life/issues/4), [#5](https://github.com/spksoft/terng.life/issues/5), [#6](https://github.com/spksoft/terng.life/issues/6), [#7](https://github.com/spksoft/terng.life/issues/7), [#8](https://github.com/spksoft/terng.life/issues/8), [#9](https://github.com/spksoft/terng.life/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@spksoft 2 puzzles [#2](https://github.com/spksoft/terng.life/issues/2), [#3](https://github.com/spksoft/terng.life/issues/3) are still not solved; solved: [#4](https://github.com/spksoft/terng.life/issues/4), [#5](https://github.com/spksoft/terng.life/issues/5), [#6](https://github.com/spksoft/terng.life/issues/6), [#7](https://github.com/spksoft/terng.life/issues/7), [#8](https://github.com/spksoft/terng.life/issues/8), [#9](https://github.com/spksoft/terng.life/issues/9).

**Comment by 0pdd** [comment]
@spksoft all 8 puzzles are solved here: [#2](https://github.com/spksoft/terng.life/issues/2), [#3](https://github.com/spksoft/terng.life/issues/3), [#4](https://github.com/spksoft/terng.life/issues/4), [#5](https://github.com/spksoft/terng.life/issues/5), [#6](https://github.com/spksoft/terng.life/issues/6), [#7](https://github.com/spksoft/terng.life/issues/7), [#8](https://github.com/spksoft/terng.life/issues/8), [#9](https://github.com/spksoft/terng.life/issues/9).
